// herramientas_build_systems_y_tecnologias_emergentes/tiendaOnlineAngularJs/src/app/carrito/carrito.component.ts
import { Component, OnInit } from '@angular/core';
// import { Response } from '@angular/http';
import { Router } from '@angular/router';
import { HttpService } from './../servicios/http.service';

@Component({
  selector: 'ang2-carrito',
  templateUrl: './carrito.component.html',
  styleUrls: ['./carrito.component.css']
})

export class CarritoComponent implements OnInit {
	public productos: string[] = [];
  public valorTotal: number;

  constructor(private httpService: HttpService, private router: Router) { }

  ngOnInit() {
  	this.obtenerProductosCarrito()

  }

  obtenerProductosCarrito() {
    let total: number = 0;
  	this.productos = this.httpService.getProductosCarrito()
    this.productos.map(function (prd, key) {
      total += prd["cantidad_solicitada"] * prd["valor"]
    })

    this.valorTotal = total
  }

  pagarPedido() {
    // Afectar BD
    this.httpService.getPagarPedido()
    // Redireccionar
    // this.router.navigate(['/catalogo']);
  }
}

<div class="row">
  <ang2-menu [cantidadProductosCarrito]="productos.length" class="column no-padding"></ang2-menu>
</div>
<div class=" row ">
  <div class="carrito">
    <div class="row small-12 linea-bottom">
      <div class="column">
        <h4>Carrito de Compras</h4>
      </div>
      <div class="column">
      </div>
    </div>
    <div class="row small-12 ">
      <!-- Columna de productos -->
      <div class="column small-6">
        <div class="row small-12 producto_carrito" *ngFor="let producto of productos">
          <div class="column small-4">
            <img src="../../assets/img/productos/{{producto.imagen}}" alt="">
          </div>
          <div class="column small-8">
            <p><strong class="column">Nombre:</strong>&nbsp;&nbsp;{{producto.nombre}}</p>
            <p><strong class="column">Cantidad:</strong>&nbsp;&nbsp;{{producto.cantidad_solicitada}}</p>
            <p><strong class="column">Subtotal:</strong>&nbsp;&nbsp;${{producto.valor * producto.cantidad_solicitada|number}}</p>
          </div>
        </div>
      </div>
      <div class="column ">
        <h2><strong>Total</strong>: ${{valorTotal|number}}</h2>
        <div class="column small-6">
          <div class="small stacked-for-small button-group">
            <input type="button" class="hollow button secondary" value="Cancelar" >
            <input (click)="pagarPedido()" type="button" class=" button warning" value="Pagar" >
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// herramientas_build_systems_y_tecnologias_emergentes/tiendaOnlineReactJs/componentes/app/Carrito.jsx
import React, { Component } from 'react';

import Menu from './Menu.jsx';

class Carrito extends Component {

	constructor(props) {
		super(props);
		this.state = {
		  productos: [],
		  prdSeleccionado: []
		}
	}

	render() {
		return (
	      	<section className="body">
	      	<Menu cantidadProductosCarrito={this.state.prdSeleccionado.length}></Menu>

			<div className=" row ">
			  <div className="carrito">
			    <div className="row small-12 linea-bottom">
			      <div className="column">
			        <h4>Carrito de Compras</h4>
			      </div>
			      <div className="column">
			      </div>
			    </div>
			    <div className="row small-12 ">
			      
			      <div className="column small-6">
			        <div className="row small-12 producto_carrito" >
			          <div className="column small-4">
			            <img src="./../assets/img/productos/ajo.jpg" alt="" />
			          </div>
			          <div className="column small-8">
			            <p><strong className="column">Nombre:</strong>&nbsp;&nbsp;NOMBRE</p>
			            <p><strong className="column">Cantidad:</strong>&nbsp;&nbsp;25</p>
			            <p><strong className="column">Subtotal:</strong>&nbsp;&nbsp;20.000</p>
			          </div>
			        </div>

			        <div className="row small-12 producto_carrito" >
			          <div className="column small-4">
			            <img src="./../assets/img/productos/ajo.jpg" alt="" />
			          </div>
			          <div className="column small-8">
			            <p><strong className="column">Nombre:</strong>&nbsp;&nbsp;NOMBRE</p>
			            <p><strong className="column">Cantidad:</strong>&nbsp;&nbsp;25</p>
			            <p><strong className="column">Subtotal:</strong>&nbsp;&nbsp;20.000</p>
			          </div>
			        </div>

			      </div>
			      <div className="column padding-horizontal-2">
			        <h2><strong>Total</strong>: $20.000</h2>
			        <div className="column small-6">
			          <div className="small stacked-for-small button-group">
			            <input type="button" className="hollow button secondary" value="Cancelar" />
			            <input type="button" className=" button warning" value="Pagar" />
			          </div>
			        </div>
			      </div>
			    </div>
			  </div>
			</div>

	      </section>
		);
	}
}

export default Carrito;
