// herramientas_build_systems_y_tecnologias_emergentes/tiendaOnlineAngularJs/src/app/inicio/inicio.component.ts
import { Component, OnInit } from '@angular/core';
import { Response } from '@angular/http';
import { HttpService } from './../servicios/http.service';

@Component({
  selector: 'ang2-inicio',
  templateUrl: './inicio.component.html',
  styleUrls: ['./inicio.component.css']
})
export class InicioComponent implements OnInit {
  public datoProductos: string[] = [];
  public datoProductosAux: string[] = [];

  constructor(private httpService: HttpService) { }

  ngOnInit() {
    this.getProductos();
  }

  getProductos() {

    this.httpService.getProductos()
      .subscribe(
      (data) => {
        let aux: any[] = [];
        for (let key in data) {
          aux.push(data[key])
        }
        this.datoProductos = aux;
        this.datoProductosAux = aux;
      },
      (error) => { return error }
    );

  }

  filtrarProductos(nombreProducto: string) {

    this.datoProductos = this.datoProductosAux.filter(
      item => {
        if (item["nombre"] !== null && item["nombre"].toLowerCase().indexOf(nombreProducto.toLowerCase()) > -1) {

            return item; 
        }
        return false;

      }
    )
  }

}

<section class="body">
  <div class="row *ngIf">
    <ang2-menu class="column no-padding"></ang2-menu>
  </div>
  <div class=" row ">
    <div class="catalogo">
      <div class="row small-12 linea-bottom">
        <div class="column">
          <h4>Catálogo de productos</h4>
        </div>
        <div class="column small-offset-5">
          <strong>¿Que estas buscando?</strong>
          <input type="text" #buscar_producto placeholder="Buscar producto" (keyup)="filtrarProductos(buscar_producto.value)" >
        </div>
      </div>
      <div class="row">
        <div class="small-12 medium-4 large-3 column" *ngFor="let producto of datoProductos">

          <div class="card">
            <div class="text-center">
              <img class="" src="../../assets/img/productos/{{producto.imagen}}">
            </div>
            <div class="card-section">
              <p><strong>{{producto.nombre}}</strong></p>
              <p>Precio: ${{producto.valor|number}}</p>
              <p>Unidades disponibles: {{producto.cantidad}}</p>
          
                <div class=" row small-12 padding-horizontal-1">
                  <a class="small-4 button primary" routerLink="/catalogo/{{producto.id}}">Ver más</a>
                  <!-- <input type="button"  value="Ver más"> -->
                  <input type="button" class="small-offset-1 small-3 button warning" value="Añadir">
                  <input type="number" class="column text-right" value="" maxlength="3">
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

// herramientas_build_systems_y_tecnologias_emergentes/tiendaOnlineReactJs/componentes/app/Inicio.jsx
import React from 'react';
import * as request from 'superagent';
// import _ from 'lodash';
import { AsyncStorage } from 'AsyncStorage';
import { NavLink } from 'react-router-dom';

import Menu from './Menu.jsx';

let url = "http://127.0.0.1/portafolioNextU/herramientas_build_systems_y_tecnologias_emergentes/webServices/ws.php?query=";
class Inicio extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      productos: []
    }
  }

  componentWillMount() {
    // console.log("component url " + url);
    request
      .get(url+"productos")
      // .then()
      .set('Content-Type': 'application/json')
      .end((err, res) => {
        // console.log('RESPONSE',  res);
        if (err || !res.ok) {
          console.log('ERRR ', err);
        } else {

          this.setState({ productos : JSON.parse(res.text)});
        }
      });
  }

  render() {

    return ( 
      <section className="body">
        <Menu></Menu>
        <div className=" row ">
          <div className="catalogo">
            <div className="row small-12 linea-bottom">
              <div className="column">
                <h4>Catálogo de productos </h4>
              </div>
              <div className="column small-offset-5">
                <strong>¿Que estas buscando?</strong>
                <input type="text" placeholder="Buscar producto" />
              </div>
            </div>
            <div className="row">
              { this.state.productos.map((prd, i) => 
              <div className="small-12 medium-4 large-3 column" key={prd.id.toString()}>
                <div className="card">
                  <div className="text-center">
                    <img className="" src={'./assets/img/productos/'+prd.imagen} />
                  </div>
                  <div className="card-section">
                    <p><strong>{prd.nombre}</strong></p>
                    <p>Precio: ${prd.valor}</p>
                    <p>Unidades disponibles: {prd.cantidad}</p>
                
                      <div className=" row small-12 padding-horizontal-1">
                        <NavLink to={'/catalogo/'+prd.id} className="small-4 button primary">Ver más</NavLink>
                        <input type="button" className="small-offset-1 small-3 button warning" value="Añadir" />
                        <input type="number" className="column text-right" value="" />
                      </div>
                  </div>
                </div>
              </div>
              )}
            </div>
          </div>
        </div>
      </section>
    );
  }

}

export default Inicio;
