// herramientas_build_systems_y_tecnologias_emergentes/tiendaOnlineAngularJs/src/app/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'ang2-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {

  constructor(private router: Router) { }

  ngOnInit() {

  	if(localStorage.getItem("currentUserIdAng") == null) {
      this.router.navigate(['/login']);
    }

  }

  salir() {
    localStorage.removeItem("currentUserIdAng");
    this.router.navigate(['/login']);
  }

}

<div class="barra_menu clearfix">
  <ul class="menu float-left">
    <li class="menu-text">La Bodega</li>
  </ul>
  
  <ul class="menu float-right">
    <li routerLinkActive="activo">
      <a routerLink="/catalogo"> <i class="fa fa-th"></i> </a>
    </li>
    <li routerLinkActive="activo">
      <a routerLink="/carrito"> <i class="fa fa-shopping-cart"></i> </a>
    </li>
    <li routerLinkActive="activo">
      <a (click) = "salir()"> <i class="fa fa-sign-out"></i> </a>
    </li>
  </ul>
</div>

// herramientas_build_systems_y_tecnologias_emergentes/tiendaOnlineReactJs/componentes/app/Menu.jsx
import React, { Component } from 'react';
import { NavLink } from 'react-router-dom';

class Menu extends Component {

	salir () {
		localStorage.removeItem("currentUserIdReact");
    	location.reload(true)
	}

	render() {
		return (
	      <div className="barra_menu clearfix">
	        <ul className="menu float-left">
	          <li className="menu-text">La Bodega</li>
	        </ul>
	        
	        <ul className="menu float-right">
	          <li >
	            <NavLink to="/"> <i className="fas fa-th"></i> </NavLink>
	          </li>
	          <li >
	            <NavLink to="/carrito"> <i className="fas fa-shopping-cart"></i> </NavLink>
	          </li>
	          <li >
	            <a href="#" onClick = {this.salir} > <i className="fas fa-sign-out-alt"></i> </a> 
	          </li>
	        </ul>
	        
	      </div>
		);
	}
}

export default Menu;
