// herramientas_build_systems_y_tecnologias_emergentes/tiendaOnlineAngularJs2/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Response } from '@angular/http';
import { Router } from '@angular/router';
import { HttpService } from './../servicios/http.service';

@Component({
  selector: 'ang2-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  providers: []
})

export class LoginComponent implements OnInit {
  public datoLogin: string[] = [] ;
  public show: string = 'hide';

  constructor(private httpService: HttpService, private router: Router) { }

  ngOnInit() {
    if(parseInt(localStorage.getItem("currentUserIdAng")) > 0) {
      this.router.navigate(['/catalogo']);
    }
  }

  enviarFormulario(f) {

    var info = f.form._value;
    this.httpService.logearse(info.correo, info.contrasenia)
    .subscribe(
      (data) => { 
        let aux : any[] = [];
        for(let key in data){
          aux.push(data[key])
        }
        this.datoLogin = aux;
        if(this.datoLogin.length > 0){
          localStorage.setItem('currentUserIdAng', this.datoLogin[0]);
          this.router.navigate(['/catalogo']);
        } else {
          // console.log(this.datoLogin);
          this.show = "";
        }
      },
      (error) => { 
        console.log(error);
        return error
       }
  );
    
  }

}

<section class="body">
  <div class="container">
    <section class="row form_login">
      <form class="small-offset-3 small-6 form" (ngSubmit)="enviarFormulario(f)" #f="ngForm">
        <strong>Correo Electrónico</strong>
        <input type="email" value="" required ngModel name="correo" />
        <strong>Contraseña</strong>
        <input type="password" value="" required ngModel name="contrasenia" />
        <div class="row column small-12 {{show}} padding-bottom-1 " id="error_login">
          <span class="label alert"><i class="fa fa-close"></i> Correo electrónico y/o la contraseña no son validos</span>
        </div>

        <div class="text-right">
          <button type="submit" class="button success"><strong>Ingresar</strong></button>
        </div>
      </form>
    </section>
  </div>
</section>

// herramientas_build_systems_y_tecnologias_emergentes/tiendaOnlineReactJs/componentes/login/Login.jsx
import React from 'react';
import * as request from 'superagent';
import { NavLink } from 'react-router-dom';

var url = "http://127.0.0.1/portafolioNextU/herramientas_build_systems_y_tecnologias_emergentes/webServices/ws.php?query=";

class Login extends React.Component{

  constructor(props) {
    super(props);
    this.state = {
      correo: '',
      contrasenia: '',
      logeado: false,
    }

    this.logearse = this.logearse.bind(this)
    this.cambiosInput = this.cambiosInput.bind(this)
  }

  logearse(event){
    event.preventDefault();

    if(this.state.correo != "" && this.state.contrasenia != "") {
      console.log(url+"login")
      request
        .post(url+"login")
        .set('Content-Type': 'application/json')
        .field({
          // query: 'login',
          correo: this.state.correo,
          contrasenia: this.state.contrasenia
        })
        .end((err, res) => {
          if (err || !res.ok) {
            console.log('ERRR ', err);
          } else {
            res = JSON.parse(res.text)
            if(Array.isArray(res)){
              alert("Usuario y/o contraseña errados");

            } else {
              // console.log('Reseee',  res);
              localStorage.setItem('currentUserIdReact', res.id);
              location.reload(true)
            }
          }
        });

    } else {
      console.log(" Alert " + this.state.correo);

    }
  }

  cambiosInput(e){
    this.setState({[e.target.name]: e.target.value});    
  }

  render() {
    // console.log("render");
    return (
      <div>
        <section className="row form_login">
          <form onSubmit={this.logearse} className="small-offset-3 small-6 form">
            <strong>Correo Electrónico</strong>
            <input type="email" name="correo" value={this.state.correo} placeholder="Escriba su Correo Electrónico" required onChange={this.cambiosInput} />
            <strong>Contraseña</strong>
            <input type="password" name="contrasenia" value={this.state.contrasenia} placeholder="Escriba su Contraseña" required onChange={this.cambiosInput}  />
            <div className="text-center">
              <button className="button success padding-horizontal-1" type="submit" >Ingresar</button>
            </div>
          </form>
        </section>
      </div>
   );
 }

  // componentDidMount() {
  //   console.log(" componentDidMount ");
  // }

}

export default Login;
